# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  analyzerlextaticoapi:
    image: ${DOCKER_REGISTRY-}analyzerlextaticoapi
    container_name: analyzer_lextatico_api
    build:
      context: .
      dockerfile: src/Analyzer.Lextatico.Api/Dockerfile
    networks:
      - Lextatico
    ports:
      - 9004:9004
      - 9005:9005
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
