# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  lextaticoapi:
    image: ${DOCKER_REGISTRY-}lextaticoapi
    build:
      context: .
      dockerfile: src/Lextatico.Api/Dockerfile
    depends_on: 
     - sqlserver
    networks:
     - Lextatico
    ports:
      - 5000:5000
      - 5001:5001
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment: 
      - SA_PASSWORD={DB_PASSWORD}
      - ACCEPT_EULA=Y
    volumes: 
      - sqlserverdata:/var/opt/mssql
    ports: 
      - 1433:1433
    networks: 
      - Lextatico
  
volumes: 
  sqlserverdata:
    external: false

networks: 
  Lextatico:
    external: true
    driver: bridge
