# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  lextaticoapi:
    image: ${DOCKER_REGISTRY-}lextaticoapi
    container_name: lextatico_api
    build:
      context: .
      dockerfile: src/Lextatico.Api/Dockerfile
    depends_on:
      - sqlserver
    networks:
      - Lextatico
    ports:
      - 9002:9002
      - 9003:9003
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - LOCAL_DEVELOPMENT=True
    volumes:
      - ~/.vsdbg:/remote_debugger:rw

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - SA_PASSWORD=L&xt@t1c02021
      - ACCEPT_EULA=Y
    volumes:
      - sqlserverdata:/var/opt/mssql
    ports:
      - 1433:1433
    networks:
      - Lextatico
